// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_School_API.Data;

namespace Project_School_API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190619122902_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Project_School_API.Models.Aluno", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("Professorid");

                    b.Property<string>("dataNasc");

                    b.Property<int>("idProfessor");

                    b.Property<string>("nome");

                    b.Property<string>("sobrenome");

                    b.HasKey("id");

                    b.HasIndex("Professorid");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("Project_School_API.Models.Professor", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("nome");

                    b.HasKey("id");

                    b.ToTable("Professores");
                });

            modelBuilder.Entity("Project_School_API.Models.Aluno", b =>
                {
                    b.HasOne("Project_School_API.Models.Professor", "Professor")
                        .WithMany("alunos")
                        .HasForeignKey("Professorid");
                });
#pragma warning restore 612, 618
        }
    }
}
